version: '3'

services:
    redis-server:
        image: "redis"

    node-app:
        restart: on-failure
        build: .
        ports:
            - "10000:8080"
        volumes:
            - /usr/app/node_modules
            - ./:/usr/app