version: '3'

services:
    redis-server:
        image: "redis"

    node-app:
        restart: on-failure
        build: .
        ports:
            - "10000:8080"
        volumes:
            # - /mnt/wdredp01/nodejs/udemy-nodejs-redis-03:/usr/app
            - ./:/usr/app